import { z } from "zod";

export const TABLES = {
  settings: z.object({
    key: z.string(),
    value: z.string().nullable(),
  }),
  filters: z.object({
    kind: z.enum(["title_include", "title_exclude", "location_include", "location_exclude", "us_tokens", "title_noise", "agency_name_patterns", "agency_blocklist"]),
    pattern: z.string(),
    note: z.string().nullable(),
  }),
  postings: z.object({
    key: z.string(),
    source: z.string(),
    company: z.string(),
    title: z.string(),
    url: z.string().nullable(),
    location: z.string().nullable(),
    remote: z.number().nullable(),
    compensation: z.string().nullable(),
    posted_at: z.string().nullable(),
    description: z.string().nullable(),
    expired: z.number(),
    comp_min: z.number().nullable(),
    comp_max: z.number().nullable(),
    comp_period: z.enum(["HOURLY", "DAILY", "WEEKLY", "BIWEEKLY", "MONTHLY", "YEARLY"]).nullable(),
    raw: z.string().nullable(),
    first_fetched: z.string(),
    last_fetched: z.string(),
    ingested_on: z.string().nullable(),
    disposition: z.enum(["kept", "title", "location", "stale", "seen", "duplicate", "expired", "agency", "noise", "lowball"]).nullable(),
    canonical_key: z.string().nullable(),
    first_seen: z.string().nullable(),
    last_seen: z.string().nullable(),
    score: z.number().nullable(),
    reason: z.string().nullable(),
    resume: z.string().nullable(),
    status: z.enum(["new", "scored", "shortlisted", "skipped", "staged", "applied", "interviewing", "rejected", "not_pursued", "closed"]).nullable(),
  }),
  events: z.object({
    id: z.number(),
    key: z.string(),
    at: z.string(),
    status: z.string().nullable(),
    note: z.string().nullable(),
  }),
  staged: z.object({
    key: z.string(),
    url: z.string().nullable(),
    screenshot: z.string().nullable(),
    status: z.enum(["ready", "blocked"]).nullable(),
    blocked_on: z.string().nullable(),
  }),
  staged_fields: z.object({
    key: z.string(),
    label: z.string(),
    value: z.string().nullable(),
    tier: z.enum(["identity", "policy", "judgment"]).nullable(),
    flag: z.string().nullable(),
  }),
  identity: z.object({
    id: z.number(),
    full_name: z.string().nullable(),
    preferred_name: z.string().nullable(),
    last_name: z.string().nullable(),
    email: z.string().nullable(),
    phone: z.string().nullable(),
    location: z.string().nullable(),
    street_address: z.string().nullable(),
    linkedin: z.string().nullable(),
    github: z.string().nullable(),
    authorized_in_country_of_residence: z.number().nullable(),
    legal_right_to_work_without_sponsorship: z.number().nullable(),
    requires_sponsorship_now_or_future: z.number().nullable(),
    over_18: z.number().nullable(),
    earliest_daily_start: z.string().nullable(),
    notice_period: z.enum(["none", "1_week", "2_weeks", "3_weeks", "1_month", "2_months", "3_months"]).nullable(),
    employment_type: z.enum(["full_time", "part_time", "contract", "internship", "temporary"]).nullable(),
    remote_preference: z.enum(["remote", "hybrid", "on_site", "no_preference"]).nullable(),
    willing_to_relocate: z.number().nullable(),
    compensation_floor: z.number().nullable(),
    compensation_currency: z.string().nullable(),
    gender: z.enum(["male", "female", "non_binary", "decline_to_say"]).nullable(),
    race_ethnicity: z.enum(["american_indian_or_alaska_native", "asian", "black_or_african_american", "hispanic_or_latino", "native_hawaiian_or_pacific_islander", "white", "two_or_more_races", "decline_to_say"]).nullable(),
    hispanic_or_latino: z.enum(["yes", "no", "decline_to_say"]).nullable(),
    veteran_status: z.enum(["protected_veteran", "not_a_protected_veteran", "decline_to_say"]).nullable(),
    disability_status: z.enum(["yes", "no", "decline_to_say"]).nullable(),
  }),
  education: z.object({
    id: z.number(),
    degree: z.string(),
    institution: z.string().nullable(),
    finished: z.string().nullable(),
  }),
  employers: z.object({
    id: z.number(),
    name: z.string(),
    title: z.string().nullable(),
    start: z.string().nullable(),
    finish: z.string().nullable(),
    current: z.number(),
    context: z.string().nullable(),
    seq: z.number().nullable(),
  }),
  projects: z.object({
    id: z.number(),
    employer_id: z.number(),
    name: z.string(),
    start: z.string().nullable(),
    finish: z.string().nullable(),
    status: z.enum(["shipped", "in_progress", "discontinued"]).nullable(),
    summary: z.string().nullable(),
    shared_with: z.string().nullable(),
    notes: z.string().nullable(),
    seq: z.number().nullable(),
  }),
  project_bullets: z.object({
    project_id: z.number(),
    seq: z.number().nullable(),
    text: z.string(),
  }),
  project_technologies: z.object({
    project_id: z.number(),
    technology: z.string(),
  }),
  project_metrics: z.object({
    project_id: z.number(),
    metric: z.string(),
  }),
  project_links: z.object({
    project_id: z.number(),
    label: z.string(),
    url: z.string(),
  }),
  instructions: z.object({
    id: z.number(),
    text: z.string().nullable(),
  }),
};
