import fs from "node:fs";
import path from "node:path";
import { z } from "zod";

import { ROOT } from "../lib/core/root.ts";
import { DERIVED, ORDER, SECTIONS, TABLES, VIEWS } from "../lib/core/schema.ts";

type Column = { sql?: string; takes?: string; kind?: string; note?: string };
type Shape = {
  note?: string;
  constraints?: string[];
  indexes?: string[];
  singleRow?: boolean;
};

const OUT = path.join(ROOT, "sql", "tables.sql");

const bare = (shape: z.ZodType): z.ZodType =>
  shape instanceof z.ZodNullable ? bare(shape.unwrap() as z.ZodType) : shape;

const kindOf = (shape: z.ZodType, said?: string) => said ?? (bare(shape) instanceof z.ZodNumber ? "INTEGER" : "TEXT");

const enumCheck = (name: string, shape: z.ZodType) => {
  const inner = bare(shape);
  if (!(inner instanceof z.ZodEnum)) return "";
  const listed = inner.options.map((held) => `'${String(held)}'`);
  const one = `CHECK (${name} IN (${listed.join(",")}))`;
  if (one.length <= 92) return one;
  const wrapped: string[] = [];
  let line = "";
  for (const held of listed) {
    if (line && line.length + held.length + 1 > 62) {
      wrapped.push(line);
      line = "";
    }
    line += (line ? "," : "") + held;
  }
  if (line) wrapped.push(line);
  const pad = " ".repeat(18);
  return `CHECK (${name} IN (\n${wrapped.map((held) => pad + held).join(",\n")}))`;
};

function declare(table: string, shape: z.ZodObject) {
  const meta = (shape.meta() ?? {}) as Shape;
  const fields = Object.entries(shape.shape) as [string, z.ZodType][];
  const width = Math.max(...fields.map(([name]) => name.length), meta.singleRow ? 2 : 0);

  const lines: { body: string; note?: string }[] = fields.map(([name, held]) => {
    const column = (held.meta() ?? {}) as Column;
    const nullable = held.safeParse(null).success;
    const parts = [
      kindOf(held, column.kind),
      !nullable && !column.sql?.includes("PRIMARY KEY") ? "NOT NULL" : "",
      column.sql ?? "",
      enumCheck(name, held),
    ].filter(Boolean);
    return {
      body: `  ${name.padEnd(width)} ${parts.join(" ")}`,
      note: column.note,
    };
  });

  if (meta.singleRow)
    lines.unshift({
      body: `  ${"id".padEnd(width)} INTEGER PRIMARY KEY CHECK (id = 1)`,
    });

  for (const held of meta.constraints ?? []) lines.push({ body: `  ${held}` });

  const rendered = lines
    .map((held, n) => held.body + (n < lines.length - 1 ? "," : "") + (held.note ? `             -- ${held.note}` : ""))
    .join("\n");

  const note = meta.note
    ? meta.note
        .split("\n")
        .map((l) => `-- ${l}`)
        .join("\n") + "\n"
    : "";
  const seed = meta.singleRow ? `\nINSERT OR IGNORE INTO ${table}(id) VALUES (1);` : "";
  const indexes = (meta.indexes ?? []).map((held) => `\nCREATE INDEX IF NOT EXISTS ${held};`).join("");

  return `${note}CREATE TABLE IF NOT EXISTS ${table} (\n${rendered}\n) STRICT;${seed}${indexes}`;
}

const view = (name: keyof typeof VIEWS) => {
  const spec = DERIVED[name]!;
  const listed = Object.keys((VIEWS[name] as z.ZodObject).shape);
  const lines: string[] = [];
  let line = "";
  for (const held of listed) {
    if (line && line.length + held.length + 2 > 62) {
      lines.push(line);
      line = "";
    }
    line += (line ? ", " : "") + held;
  }
  if (line) lines.push(line);
  return (
    `DROP VIEW IF EXISTS ${name};\nCREATE VIEW ${name} AS\n  SELECT ` +
    lines.join(",\n         ") +
    `\n  FROM postings WHERE ${spec.where}` +
    (spec.order ? `\n  ORDER BY ${spec.order}` : "") +
    ";"
  );
};

const answers = () => {
  const listed = Object.keys(TABLES.identity.shape);
  const pairs: string[] = [];
  let line = "";
  for (const held of listed) {
    const pair = `'${held}', ${held}`;
    if (line && line.length + pair.length + 2 > 74) {
      pairs.push(line);
      line = "";
    }
    line += (line ? ", " : "") + pair;
  }
  if (line) pairs.push(line);
  return `-- Every question a form could ask, and whatever the profile says back. Phase 4
-- checks \`unanswered\` before staging; anything listed there blocks rather than
-- gets guessed. Generated from the identity shape, so a column added there
-- appears here on the next \`npm run schema\`.
DROP VIEW IF EXISTS unanswered;
DROP VIEW IF EXISTS answers;
CREATE VIEW IF NOT EXISTS answers AS
  SELECT section, answer.key AS field, answer.value AS value FROM (
    SELECT 'identity' AS section, json_object(
${pairs.map((held) => "             " + held).join(",\n")}) AS row
      FROM identity
    UNION ALL SELECT 'experience', json_object(
             'years', years, 'relevant_years', relevant_years,
             'clock_starts', clock_starts) FROM experience
  ), json_each(row) AS answer;

CREATE VIEW IF NOT EXISTS unanswered AS
  SELECT section, field FROM answers WHERE value IS NULL;`;
};

const body = [
  "-- Generated by `npm run schema` from lib/core/schema.ts. Do not edit.",
  "-- Views, triggers and seeds that Zod cannot express live in sql/logic.sql.",
  "",
  "PRAGMA journal_mode=WAL;",
  "PRAGMA foreign_keys=ON;",
  "",
  ...ORDER.map((table) => declare(table, TABLES[table] as z.ZodObject) + "\n"),
  (Object.keys(DERIVED) as (keyof typeof VIEWS)[]).map(view).join("\n\n"),
  "",
  answers(),
  "",
].join("\n");

fs.writeFileSync(OUT, body, "utf8");

console.log(`wrote ${path.relative(ROOT, OUT)} — ${ORDER.length} tables, ${SECTIONS.length} sections`);
