-- Seed data, applied with `lib/q.py -f sql/seed.sql` against a fresh database.
-- Companies on Greenhouse, Lever and Ashby, plus the mechanical filters and settings.
-- Edit freely, or ignore it entirely and INSERT into `companies` by hand.

-- Settings -----------------------------------------------------------------
INSERT OR REPLACE INTO settings(key,value) VALUES('max_age_days','30');
INSERT OR REPLACE INTO settings(key,value) VALUES('comp_floor','100000');
INSERT OR REPLACE INTO settings(key,value) VALUES('fromage_days','7');
INSERT OR REPLACE INTO settings(key,value) VALUES('delay_ms','3000');
INSERT OR REPLACE INTO settings(key,value) VALUES('shortlist_threshold','7');

-- Filters ------------------------------------------------------------------
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_include','(?i)\b(ai|ml|llm|llms|genai|nlp|rag)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_include','(?i)machine learning|deep learning|generative ai|applied scien|research engineer|research scien|foundation model|language model|inference|evaluation');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_exclude','(?i)\b(intern|internship|apprentice|new grad|university grad|working student|co-op)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_exclude','(?i)\b(manager|director|head of|vp|vice president|chief|president)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_exclude','(?i)\b(sales|account executive|seller|recruiter|recruiting|sourcer|marketing|counsel|legal|paralegal|accountant|controller|payroll|people ops|workplace|facilities|executive assistant)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_exclude','(?i)\b(hardware|mechanical|electrical|firmware|technician|manufacturing|optical|robotics technician|vehicle operator|driver)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_exclude','(?i)\b(designer|ux researcher|content strategist|copywriter|technical writer)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_exclude','(?i)\b(support|success|sales engineer|implementation|onboarding specialist)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_exclude','(?i)\b(gtm|go-to-market|strategic finance|transformation owner|partner engineer)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_exclude','(?i)\b(adoption lead|transformation lead|deployment lead|ai strategist|enablement|ecosystem architect|growth marketer|rvp|regional vice president|deal desk|post-doctoral|postdoctoral)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('location_include','(?i)remote');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('location_include','(?i)\b(YOUR_CITY|YOUR_SUBURB|YOUR_AIRPORT_CODE)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('location_include','(?i)YOUR_STATE|,\s*XX\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('location_include','(?i)united states|u\.s\.|\busa\b|anywhere|distributed');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('location_exclude','(?i)\b(canada|ontario|toronto|vancouver, ?bc|british columbia|quebec|montreal)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('location_exclude','(?i)\b(united kingdom|uk|london|ireland|dublin|germany|berlin|munich|france|paris|netherlands|amsterdam|spain|poland|portugal|israel|tel aviv)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('location_exclude','(?i)\b(india|delhi|bangalore|bengaluru|japan|tokyo|singapore|australia|sydney|brazil|são paulo|sao paulo|mexico|emea|apac|latam)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('us_tokens','(?i)\b(us|u\.s\.|usa|united states)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('us_tokens','(?i)portland|oregon|,\s*OR\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_noise','(?i)\bai trainer\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_noise','(?i)\b(data annotat|annotation specialist|labeler|transcriptionist)');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_noise','(?i)\b(freelance|gig|side income|work from home opportunity)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_noise','(?i)\b(tutor|coach|instructor|teach)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('title_noise','(?i)\bearn (money|cash)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_name_patterns','(?i)\b(staffing|recruit(ing|ers|ment)?|talent (solutions|acquisition|group)|headhunt)');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_name_patterns','(?i)\b(consultancy|consulting services|it services|outsourc)');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_name_patterns','(?i)\bplacement|contract(ing)? services\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_name_patterns','(?i)\b(consulting group|associates,? inc|federal|govcio|gov ?con)\b');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Accenture');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Apex Systems');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Blu Omega');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Bright Vision Technologies');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Calance US');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Capgemini');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Career.io');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','ClearanceJobs');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Cognizant');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Collabera');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Comtech Global Inc');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','CyberCoders');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','DataAnnotation');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','David Joseph & Company');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Delan Associates, Inc');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Deloitte');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Dice');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Diverse Lynx');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Dreams 2 Reality Recruitment');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Govcio LLC');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','HCLTech');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Huron Consulting Group Inc.');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','ICF');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Impact Consulting Solutions, Inc.');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Infosys');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Insight Global');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Jobot');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Kforce');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','LTIMindtree');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Lanthos LLC');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Lensa');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','MGT Impact Solutions, LLC');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Mapgenesys');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Marathon TS');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Marlabs');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Matoffo');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Mindlance');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Motion Recruitment');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Next Step Systems');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Provectus');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Randstad');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Redapt');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','RevStar');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Robert Half');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','TEKsystems');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Talentify');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Tata Consultancy Services');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Technergetics');
INSERT OR IGNORE INTO filters(kind,pattern) VALUES('agency_blocklist','Wipro');

-- Watchlist ----------------------------------------------------------------
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('abridge','ashby','Abridge',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('absci','ashby','Absci',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('affirm','greenhouse','Affirm',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('airbnb','greenhouse','Airbnb',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('airbyte','ashby','Airbyte',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('airtable','greenhouse','Airtable',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('alloy','greenhouse','Alloy',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('alphasense','greenhouse','AlphaSense',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('ambiencehealthcare','ashby','Ambience Healthcare',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('amperity','greenhouse','Amperity',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('amplitude','greenhouse','Amplitude',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('anthropic','greenhouse','Anthropic',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('anyscale','ashby','Anyscale',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('arizeai','greenhouse','Arize AI',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('asana','greenhouse','Asana',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('assemblyai','greenhouse','AssemblyAI',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('baseten','ashby','Baseten',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('braintrust','ashby','Braintrust',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('brex','greenhouse','Brex',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('browserbase','ashby','Browserbase',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('buffer','ashby','Buffer',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('calendly','greenhouse','Calendly',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('chime','greenhouse','Chime',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('clickhouse','greenhouse','ClickHouse',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('cloudflare','greenhouse','Cloudflare',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('cockroachlabs','greenhouse','Cockroach Labs',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('cognition','ashby','Cognition',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('cohere','ashby','Cohere',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('coherehealth','greenhouse','Cohere Health',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('commure','ashby','Commure',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('confluent','ashby','Confluent',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('coreweave','greenhouse','CoreWeave',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('corti','ashby','Corti',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('coursera','greenhouse','Coursera',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('disco','greenhouse','CS Disco',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('cursor','ashby','Cursor (Anysphere)',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('databricks','greenhouse','Databricks',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('datadog','greenhouse','Datadog',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('decagon','ashby','Decagon',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('deepgram','ashby','Deepgram',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('deepnote','ashby','Deepnote',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('digimarc','greenhouse','Digimarc',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('dropbox','greenhouse','Dropbox',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('duolingo','greenhouse','Duolingo',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('e2b','ashby','E2B',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('elastic','greenhouse','Elastic',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('elevenlabs','ashby','ElevenLabs',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('eve','greenhouse','Eve',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('everlaw','greenhouse','Everlaw',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('feedzai','greenhouse','Feedzai',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('figma','greenhouse','Figma',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('fivetran','greenhouse','Fivetran',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('flexport','greenhouse','Flexport',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('gitlab','greenhouse','GitLab',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('gleanwork','greenhouse','Glean',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('gusto','greenhouse','Gusto',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('harvey','ashby','Harvey',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('hex','ashby','Hex',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('hightouch','greenhouse','Hightouch',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('insitro','ashby','Insitro',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('instacart','greenhouse','Instacart',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('intercom','greenhouse','Intercom',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('jamasoftware','greenhouse','Jama Software',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('khanacademy','greenhouse','Khan Academy',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('langchain','ashby','LangChain',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('langfuse','ashby','Langfuse',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('layerhealth','greenhouse','Layer Health',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('linear','ashby','Linear',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('llamaindex','ashby','LlamaIndex',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('mercury','greenhouse','Mercury',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('middesk','ashby','Middesk',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('mixpanel','greenhouse','Mixpanel',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('modal','ashby','Modal',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('moderntreasury','ashby','Modern Treasury',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('mongodb','greenhouse','MongoDB',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('montecarlodata','ashby','Monte Carlo',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('nabla','ashby','Nabla',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('neon','ashby','Neon',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('newrelic','greenhouse','New Relic',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('notion','ashby','Notion',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('nuro','greenhouse','Nuro',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('observeai','greenhouse','Observe.AI',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('omni','ashby','Omni',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('openai','ashby','OpenAI',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('openevidence','ashby','OpenEvidence',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('opensesame','greenhouse','OpenSesame',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('palantir','lever','Palantir',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('parloa','greenhouse','Parloa',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('peloton','greenhouse','Peloton',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('perplexity','ashby','Perplexity',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('pinecone','ashby','Pinecone',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('pinterest','greenhouse','Pinterest',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('plaid','ashby','Plaid',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('poolside','ashby','Poolside',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('posthog','ashby','PostHog',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('prefect','ashby','Prefect',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('railway','ashby','Railway',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('ramp','ashby','Ramp',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('reddit','greenhouse','Reddit',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('regard','ashby','Regard',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('relativity','greenhouse','Relativity',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('render','ashby','Render',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('replit','ashby','Replit',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('ridgeline','greenhouse','Ridgeline',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('robinhood','greenhouse','Robinhood',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('rogo','ashby','Rogo',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('runpod','ashby','RunPod',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('runway','ashby','Runway (finance)',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('samsara','greenhouse','Samsara',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('sardine','ashby','Sardine',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('scaleai','greenhouse','Scale AI',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('shieldai','lever','Shield AI',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('sierra','ashby','Sierra',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('smarsh','lever','Smarsh',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('snowflake','ashby','Snowflake',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('socure','ashby','Socure',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('squarespace','greenhouse','Squarespace',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('starburst','greenhouse','Starburst',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('stripe','greenhouse','Stripe',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('suki','greenhouse','Suki',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('supabase','ashby','Supabase',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('sweep','ashby','Sweep',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('tavily','ashby','Tavily',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('temporal','ashby','Temporal',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('togetherai','greenhouse','Together AI',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('twitch','greenhouse','Twitch',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('typeface','greenhouse','Typeface',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('udemy','greenhouse','Udemy',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('vanta','ashby','Vanta',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('vercel','greenhouse','Vercel',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('verkada','greenhouse','Verkada',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('warp','ashby','Warp',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('waymo','greenhouse','Waymo',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('weaviate','ashby','Weaviate',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('webflow','greenhouse','Webflow',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('writer','ashby','Writer',1,'seed');
INSERT OR IGNORE INTO companies(slug,ats,name,active,source) VALUES('zapier','ashby','Zapier',1,'seed');
