-- Generated by `npm run schema` from lib/core/schema.ts. Do not edit.
-- Views, triggers and seeds that Zod cannot express live in sql/logic.sql.

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value TEXT
) STRICT;

CREATE TABLE IF NOT EXISTS filters (
  kind    TEXT NOT NULL CHECK (kind IN (
                  'title_include','title_exclude','location_include',
                  'location_exclude','us_tokens','title_noise',
                  'agency_name_patterns','agency_blocklist')),
  pattern TEXT NOT NULL,
  note    TEXT,
  PRIMARY KEY (kind, pattern)
) STRICT;

CREATE TABLE IF NOT EXISTS postings (
  key           TEXT PRIMARY KEY,
  source        TEXT NOT NULL,
  company       TEXT NOT NULL,
  title         TEXT NOT NULL,
  url           TEXT CHECK (url LIKE 'http%://%.%'),
  location      TEXT,
  remote        INTEGER CHECK (remote IN (0,1)),
  compensation  TEXT,
  posted_at     TEXT CHECK (posted_at IS NULL OR datetime(posted_at) IS NOT NULL),
  description   TEXT,
  expired       INTEGER NOT NULL DEFAULT 0 CHECK (expired IN (0,1)),
  comp_min      REAL CHECK (comp_min >= 0),
  comp_max      REAL CHECK (comp_max >= 0),
  comp_period   TEXT CHECK (comp_period IN ('HOURLY','DAILY','WEEKLY','BIWEEKLY','MONTHLY','YEARLY')),
  raw           TEXT,
  first_fetched TEXT NOT NULL DEFAULT (date('now')) CHECK (first_fetched IS date(first_fetched)),
  last_fetched  TEXT NOT NULL DEFAULT (date('now')) CHECK (last_fetched IS date(last_fetched)),
  ingested_on   TEXT CHECK (ingested_on IS date(ingested_on)),
  disposition   TEXT CHECK (disposition IN (
                  'kept','title','location','stale','seen','duplicate','expired',
                  'agency','noise','lowball')),
  canonical_key TEXT REFERENCES postings(key) ON DELETE SET NULL,
  first_seen    TEXT CHECK (first_seen IS date(first_seen)),
  last_seen     TEXT CHECK (last_seen IS date(last_seen)),
  score         INTEGER CHECK (score IS NULL OR score BETWEEN 0 AND 10),
  reason        TEXT,
  resume        TEXT,
  status        TEXT CHECK (status IN (
                  'new','scored','shortlisted','skipped','staged','applied',
                  'interviewing','rejected','not_pursued','closed')),
  CHECK (disposition IS NOT 'kept' OR canonical_key IS NULL),
  CHECK (canonical_key IS NULL OR canonical_key <> key),
  CHECK (disposition IS 'kept' OR (status IS NULL AND score IS NULL AND reason IS NULL
                                   AND resume IS NULL AND first_seen IS NULL))
) STRICT;
CREATE INDEX IF NOT EXISTS idx_postings_pending ON postings(disposition, last_fetched);
CREATE INDEX IF NOT EXISTS idx_postings_status ON postings(status);
CREATE INDEX IF NOT EXISTS idx_postings_seen ON postings(first_seen);
CREATE INDEX IF NOT EXISTS idx_postings_canonical ON postings(canonical_key);

-- History. Written by the triggers in logic.sql, never by hand.
CREATE TABLE IF NOT EXISTS events (
  id     INTEGER PRIMARY KEY AUTOINCREMENT,
  key    TEXT NOT NULL REFERENCES postings(key) ON DELETE CASCADE,
  at     TEXT NOT NULL DEFAULT (datetime('now')) CHECK (datetime(at) IS NOT NULL),
  status TEXT,
  note   TEXT
) STRICT;
CREATE INDEX IF NOT EXISTS idx_events_key ON events(key);

CREATE TABLE IF NOT EXISTS staged (
  key        TEXT PRIMARY KEY REFERENCES postings(key) ON DELETE CASCADE,
  url        TEXT CHECK (url LIKE 'http%://%.%'),
  screenshot TEXT,
  status     TEXT CHECK (status IN ('ready','blocked')),
  blocked_on TEXT
) STRICT;

CREATE TABLE IF NOT EXISTS staged_fields (
  key   TEXT NOT NULL REFERENCES postings(key) ON DELETE CASCADE,
  label TEXT NOT NULL,
  value TEXT,
  tier  TEXT CHECK (tier IN ('identity','policy','judgment')),
  flag  TEXT
) STRICT;

-- Who the applicant is, in the order a form asks: contact, then the yes/no
-- questions every form repeats, then when you could start, then the optional
-- ones. Declining to say is a real answer rather than a missing one, which is
-- why the last five are choices and not flags.
CREATE TABLE IF NOT EXISTS identity (
  id                                      INTEGER PRIMARY KEY CHECK (id = 1),
  full_name                               TEXT CHECK (trim(full_name) <> ''),
  preferred_name                          TEXT CHECK (trim(preferred_name) <> ''),
  last_name                               TEXT CHECK (trim(last_name) <> ''),
  email                                   TEXT CHECK (email LIKE '_%@_%._%'),
  phone                                   TEXT CHECK (NOT phone GLOB '*[A-Za-z]*' AND length(phone) >= 7),
  location                                TEXT CHECK (trim(location) <> ''),
  street_address                          TEXT CHECK (trim(street_address) <> ''),
  linkedin                                TEXT CHECK (linkedin LIKE 'http%://%.%'),
  github                                  TEXT CHECK (github LIKE 'http%://%.%'),
  authorized_in_country_of_residence      INTEGER CHECK (authorized_in_country_of_residence IN (0,1)),
  legal_right_to_work_without_sponsorship INTEGER CHECK (legal_right_to_work_without_sponsorship IN (0,1)),
  requires_sponsorship_now_or_future      INTEGER CHECK (requires_sponsorship_now_or_future IN (0,1)),
  over_18                                 INTEGER CHECK (over_18 IN (0,1)),
  earliest_daily_start                    TEXT CHECK (earliest_daily_start GLOB '[0-2][0-9]:[0-5][0-9]'
                                       AND earliest_daily_start <= '23:59'),
  notice_period                           TEXT CHECK (notice_period IN (
                  'none','1_week','2_weeks','3_weeks','1_month','2_months',
                  '3_months')),
  employment_type                         TEXT CHECK (employment_type IN ('full_time','part_time','contract','internship','temporary')),
  remote_preference                       TEXT CHECK (remote_preference IN ('remote','hybrid','on_site','no_preference')),
  willing_to_relocate                     INTEGER CHECK (willing_to_relocate IN (0,1)),
  compensation_floor                      INTEGER CHECK (compensation_floor >= 0),
  compensation_currency                   TEXT CHECK (compensation_currency GLOB '[A-Z][A-Z][A-Z]'),
  gender                                  TEXT CHECK (gender IN ('male','female','non_binary','decline_to_say')),
  race_ethnicity                          TEXT CHECK (race_ethnicity IN (
                  'american_indian_or_alaska_native','asian',
                  'black_or_african_american','hispanic_or_latino',
                  'native_hawaiian_or_pacific_islander','white',
                  'two_or_more_races','decline_to_say')),
  hispanic_or_latino                      TEXT CHECK (hispanic_or_latino IN ('yes','no','decline_to_say')),
  veteran_status                          TEXT CHECK (veteran_status IN ('protected_veteran','not_a_protected_veteran','decline_to_say')),
  disability_status                       TEXT CHECK (disability_status IN ('yes','no','decline_to_say'))
) STRICT;
INSERT OR IGNORE INTO identity(id) VALUES (1);

-- `finished` and the career dates below are as precise as the user was: a year,
-- a year and month, or a full date. A resume prints months, so demanding a day
-- would invent one.
CREATE TABLE IF NOT EXISTS education (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  degree      TEXT NOT NULL CHECK (trim(degree) <> ''),
  institution TEXT CHECK (trim(institution) <> ''),
  finished    TEXT CHECK (finished IS date(finished) OR date(finished || '-01') IS NOT NULL OR date(finished || '-01-01') IS NOT NULL)
) STRICT;

CREATE TABLE IF NOT EXISTS employers (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  name    TEXT NOT NULL CHECK (trim(name) <> ''),
  title   TEXT CHECK (trim(title) <> ''),
  start   TEXT CHECK (start IS date(start) OR date(start || '-01') IS NOT NULL OR date(start || '-01-01') IS NOT NULL),
  finish  TEXT CHECK (finish IS date(finish) OR date(finish || '-01') IS NOT NULL OR date(finish || '-01-01') IS NOT NULL),
  current INTEGER NOT NULL DEFAULT 0 CHECK (current IN (0,1)),
  context TEXT,
  seq     INTEGER CHECK (seq >= 0),
  CHECK (current = 0 OR finish IS NULL)
) STRICT;

-- The only source a resume may draw from. A correction lives on the row it corrects --
-- a wrong number in `project_metrics`, a wrong title on `employers`, everything else
-- in `notes` -- so there is one place to read and nothing to reconcile.
CREATE TABLE IF NOT EXISTS projects (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  employer_id INTEGER NOT NULL REFERENCES employers(id) ON DELETE CASCADE,
  name        TEXT NOT NULL CHECK (trim(name) <> ''),
  start       TEXT CHECK (start IS date(start) OR date(start || '-01') IS NOT NULL OR date(start || '-01-01') IS NOT NULL),
  finish      TEXT CHECK (finish IS date(finish) OR date(finish || '-01') IS NOT NULL OR date(finish || '-01-01') IS NOT NULL),
  status      TEXT CHECK (status IN ('shipped','in_progress','discontinued')),
  summary     TEXT,
  shared_with TEXT,             -- 'one other engineer' — how shared work stays honest
  notes       TEXT,
  seq         INTEGER CHECK (seq >= 0)
) STRICT;

CREATE TABLE IF NOT EXISTS project_bullets (
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  seq        INTEGER CHECK (seq >= 0),
  text       TEXT NOT NULL CHECK (trim(text) <> '')
) STRICT;

-- What a JD is matched against when selecting bullets.
CREATE TABLE IF NOT EXISTS project_technologies (
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  technology TEXT NOT NULL,
  PRIMARY KEY (project_id, technology)
) STRICT;

CREATE TABLE IF NOT EXISTS project_metrics (
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  metric     TEXT NOT NULL
) STRICT;

CREATE TABLE IF NOT EXISTS project_links (
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  label      TEXT NOT NULL CHECK (trim(label) <> ''),
  url        TEXT NOT NULL CHECK (url LIKE 'http%://%.%')
) STRICT;

-- What to do with everything above: the prose the search is typed from and
-- every score is judged against. One reader reads it, and typed columns only
-- flatten the slopes it describes into walls.
CREATE TABLE IF NOT EXISTS instructions (
  id   INTEGER PRIMARY KEY CHECK (id = 1),
  text TEXT CHECK (trim(text) <> '')
) STRICT;
INSERT OR IGNORE INTO instructions(id) VALUES (1);

DROP VIEW IF EXISTS prospects;
CREATE VIEW prospects AS
  SELECT key, company, title, url, location, remote, compensation,
         posted_at, first_seen, last_seen, source, description, score,
         reason, resume, status
  FROM postings WHERE disposition = 'kept';

DROP VIEW IF EXISTS triage;
CREATE VIEW triage AS
  SELECT key, company, title, location, remote, compensation, posted_at,
         first_seen, source, score, status, resume, url
  FROM postings WHERE disposition = 'kept'
  ORDER BY COALESCE(score,-1) DESC, first_seen DESC;

-- Every question a form could ask, and whatever the profile says back. Phase 4
-- checks `unanswered` before staging; anything listed there blocks rather than
-- gets guessed. Generated from the identity shape, so a column added there
-- appears here on the next `npm run schema`.
DROP VIEW IF EXISTS unanswered;
DROP VIEW IF EXISTS answers;
CREATE VIEW IF NOT EXISTS answers AS
  SELECT section, answer.key AS field, answer.value AS value FROM (
    SELECT 'identity' AS section, json_object(
             'full_name', full_name, 'preferred_name', preferred_name,
             'last_name', last_name, 'email', email, 'phone', phone,
             'location', location, 'street_address', street_address,
             'linkedin', linkedin, 'github', github,
             'authorized_in_country_of_residence', authorized_in_country_of_residence,
             'legal_right_to_work_without_sponsorship', legal_right_to_work_without_sponsorship,
             'requires_sponsorship_now_or_future', requires_sponsorship_now_or_future,
             'over_18', over_18, 'earliest_daily_start', earliest_daily_start,
             'notice_period', notice_period, 'employment_type', employment_type,
             'remote_preference', remote_preference,
             'willing_to_relocate', willing_to_relocate,
             'compensation_floor', compensation_floor,
             'compensation_currency', compensation_currency, 'gender', gender,
             'race_ethnicity', race_ethnicity, 'hispanic_or_latino', hispanic_or_latino,
             'veteran_status', veteran_status, 'disability_status', disability_status) AS row
      FROM identity
    UNION ALL SELECT 'experience', json_object(
             'years', years, 'relevant_years', relevant_years,
             'clock_starts', clock_starts) FROM experience
  ), json_each(row) AS answer;

CREATE VIEW IF NOT EXISTS unanswered AS
  SELECT section, field FROM answers WHERE value IS NULL;
